### ISSUE TITLE
Исправления в админке

### ISSUE THREAD

**Issue by rudenko-v** [milaxcom/mconsole-maps#1]
- [ ] ~~Не работает поиск по карте~~
- [x] Сделать настройку, чтобы после добавления записи мы оставались на форме добавления (очень разражает при большом объеме данных)
- [x] Поменять местами поля latitude и longitude
- [x] Скрипт вставки координат в поля latitude и longitude

Скрипт вставки:
Мы вставляем строку вида: {latitude},{longitude}
При вставке в поле строка должна разбиваться напополам по запятой и половинки вставляются в соответствующие поля.

**Comment by mindesik** [comment]
1) поиск отлично работает
3) что значит "Поменять местами поля latitude и longitude"? Координаты вставляются в соответствующие поля: http://take.ms/djqqb. Или речь идет о визуальном расположении инпутов?

**Comment by misterpaladin** [comment]
На счет 3 - локализация не верная была

**Comment by mindesik** [comment]
2) это глобально сделается в mconsole, позже
